export const EDIT_ADD_ITEM = 'EDIT_ADD_ITEM'
export const END_ADD_ITEM = 'END_ADD_ITEM'
export const ADD_NEW_ITEM = 'ADD_NEW_ITEM'

export const EDIT_EXISTING_ITEM = 'EDIT_EXISTING_ITEM'
export const UPDATE_EXISTING_ITEM = 'UPDATE_EXISTING_ITEM'
export const END_EDITING_ITEM = 'END_EDITING_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'

export const TOGGLE_ITEM_COMPLETE = 'TOGGLE_ITEM_COMPLETE'

export const TOGGLE_SHOW_COMPLETED = 'TOGGLE_SHOW_COMPLETED'
export const TOGGLE_SHOW_DELETED = 'TOGGLE_SHOW_DELETED'

export const EDIT_ITEM_DETAILS = 'EDIT_ITEM_DETAILS'
export const CLOSE_ITEM_DETAILS = 'CLOSE_ITEM_DETAILS'
export const UPDATE_ITEM_DETAILS = 'UPDATE_ITEM_DETAILS'
